name: Run Document Builder
on:
  workflow_dispatch:
jobs:
  build-docbuilder:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            tar
            xz
            curl
            unzip
            
      - name: Install Document Builder
        shell: msys2 {0}
        run: |
          ARCH=$(uname -m)
          if [[ "$ARCH" == "x86_64" ]]; then
            FILE_NAME="onlyoffice-documentbuilder-windows-x64.zip"
          else
            FILE_NAME="onlyoffice-documentbuilder-windows-x86.zip"
          fi
          echo "Using file: $FILE_NAME"
          curl -L -o "$FILE_NAME" "https://github.com/ONLYOFFICE/DocumentBuilder/releases/latest/download/$FILE_NAME"
          
          mkdir -p builder
          unzip "$FILE_NAME" -d builder

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build hello-world.exe
        run: |
          cl hello-world.cpp /Ibuilder/include builder\doctrenderer.lib /Fe:hello-world.exe

      - name: Copy DLL to exe folder
        run: copy builder\doctrenderer.dll hello-world.exe

      - name: Run the program
        run: hello-world.exe
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            result.docx
