name: Run Document Builder

on:
  workflow_dispatch:

jobs:
  build-docbuilder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Document Builder
        run: |
          ARCH=$(uname -m)
          if [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
            FILE_NAME="onlyoffice-documentbuilder-linux-aarch64.tar.xz"
          else
            FILE_NAME="onlyoffice-documentbuilder-linux-x86_64.tar.xz"
          fi
      
          curl -L -o "$FILE_NAME" "https://github.com/ONLYOFFICE/DocumentBuilder/releases/latest/download/$FILE_NAME"
          
          mkdir -p builder
          tar xvJf "$FILE_NAME" -C builder

      - name: Compile with Document Builder
        run: |
          g++ hello-world.cpp \
            -Ibuilder/opt/onlyoffice/documentbuilder/include \
            -Lbuilder/opt/onlyoffice/documentbuilder \
            -ldocbuilder.c \
            -lDocxRenderer \
            -ldoctrenderer \
            -lstdc++ -lpthread -lm -lc \
            -Wl,-rpath=builder/opt/onlyoffice/documentbuilder \
            -o hello-world
