name: Run Document Builder
on:
  workflow_dispatch:
jobs:
  build-docbuilder:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Install Document Builder
        run: |
          :: Detect architecture and set download URL
          IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (
              SET "URL=https://github.com/ONLYOFFICE/DocumentBuilder/releases/latest/download/onlyoffice-documentbuilder-windows-x64.zip"
              SET "FOLDER=onlyoffice-documentbuilder-windows-x64"
          ) ELSE (
              SET "URL=https://github.com/ONLYOFFICE/DocumentBuilder/releases/latest/download/onlyoffice-documentbuilder-windows-x86.zip"
              SET "FOLDER=onlyoffice-documentbuilder-windows-x86"
          )
          
          :: Download the archive
          curl -L -o documentbuilder.zip %URL%
          
          :: Extract the archive
          powershell -command "Expand-Archive -Path 'documentbuilder.zip' -DestinationPath '.' -Force"
      
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build hello-world.exe and run
        run: |
          cl hello-world.cpp /Ibuilder/include builder\doctrenderer.lib /Fe:hello-world.exe
          
          # Add 'builder' subfolder to PATH (relative path)
          $env:PATH = "$(Get-Location)\builder;$env:PATH"

          # run
          .\hello-world.exe
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            result.docx
