name: Run Document Builder
on:
  workflow_dispatch:
jobs:
  build-docbuilder:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            tar
            xz
            curl
            unzip
            
      - name: Install Document Builder
        run: |
          $ARCH = if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" }
          $FILE_NAME = "onlyoffice-documentbuilder-win-$ARCH.zip"
          Write-Host "Using file: $FILE_NAME"
          curl -L -o "$FILE_NAME" "https://github.com/ONLYOFFICE/DocumentBuilder/releases/latest/download/$FILE_NAME"
          
          New-Item -ItemType Directory -Force -Path "builder"
          Expand-Archive -Path "$FILE_NAME" -DestinationPath "builder" -Force
          
      - name: Compile with Document Builder and run
        shell: msys2 {0}
        run: |
          # Compile the C++ program
          g++ hello-world.cpp \
            -Ibuilder/include \
            -Lbuilder \
            -ldocbuilder \
            -o hello-world.exe
            
          # Set PATH to include the builder directory for DLLs
          export PATH="$(pwd)/builder:$PATH"
          ./hello-world.exe
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            result.docx
