name: Run Document Builder
on:
  workflow_dispatch:
jobs:
  build-docbuilder:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          # Install xz using Homebrew
          brew install xz
          # gcc/g++ should already be available via Xcode Command Line Tools
          # but we can ensure they're available
          xcode-select --install || true
          
      - name: Install Document Builder
        run: |
          ARCH=$(uname -m)
          if [[ "$ARCH" == "arm64" ]]; then
            FILE_NAME="onlyoffice-documentbuilder-macos-arm64.tar.xz"
          else
            FILE_NAME="onlyoffice-documentbuilder-macos-x86_64.tar.xz"
          fi

          echo "Using file: $FILE_NAME"

          curl -L -o "$FILE_NAME" "https://github.com/ONLYOFFICE/DocumentBuilder/releases/latest/download/$FILE_NAME"
          
          mkdir -p builder
          tar xvJf "$FILE_NAME" -C builder
      - name: Compile with Document Builder and run
        run: |
          g++ hello-world.cpp \
            -Ibuilder/include \
            -Lbuilder \
            -ldocbuilder.c \
            -lDocxRenderer \
            -ldoctrenderer \
            -lpthread \
            -o hello-world \
            -Wl,-rpath,@executable_path/builder
          ./hello-world
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            result.docx
